name: Add Github User to Allowlist on PR Review

on:
  workflow_call:
    inputs:
      github_user_id:
        type: number
        required: true
      activity_id:
        type: number
        required: true
      xps:
        type: number
        required: false

permissions:
  contents: read
  pull-requests: write

jobs:
  handle-reviewer-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Call Allowlist GitHub Action
        uses: ton-society/github-allowlist-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          x_api_key: ${{ secrets.X_API_KEY }}
          x_partner_id: ${{ secrets.X_PARTNER_ID }}
          github_user_id: ${{ inputs.github_user_id }}
          activity_id: ${{ inputs.activity_id }}
          xps: ${{ inputs.xps }}
