name: Backend health check

on:
  # schedule:
  #   - cron: "*/5 * * * *" # every 5 minutes
  workflow_dispatch:


jobs:
  request-and-parse-status:
    runs-on: ubuntu-latest
    steps:
      - name: Request status
        run: curl -X GET "https://society.ton.org/v1/status" -o status.json
      - name: Parse response
        id: parse-response
        run: echo "status=$(cat status.json | jq -c '.Status')" >> $GITHUB_OUTPUT
      - name: Print status
        run: echo ${{ steps.parse-response.outputs.status }}
