name: Backend health check

on:
  # schedule:
  #   - cron: "*/5 * * * *" # every 5 minutes
  workflow_dispatch:


jobs:
  request-and-parse-status:
    runs-on: ubuntu-latest
    steps:
      - name: Request status
        run: curl -X GET "https://society.ton.org/v1/status" -o response.json
      - name: Parse response
        id: parse-response
        run: echo "status=$(cat response.json | jq -c '.Status')" >> $GITHUB_OUTPUT
      - name: Print status
        run: echo "${{ steps.parse-response.outputs.status }}"
      - name: Send TG notification when the health check failed
        if: steps.parse-response.outputs.status != 'OK' # || ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          debug: true
          format: html
          message: |
            ton-society backend service: <b>failed health check</b>
            
            See details at https://society.ton.org/v1/status


