name: Main

on: workflow_dispatch

jobs:
  main-flow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Running index.js in MAIN
        run: node index.js
        env:
          MINIMUM: ${{ secrets.MINIMUM }}
          MAXIMUM: ${{ secrets.MAXIMUM }}

      - uses: ./.github/workflows/submodule.yml
