name: Main

on: workflow_dispatch

jobs:
  main-flow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - uses: actions/checkout@v1
        name: Checkout an Action

      - uses: ./subfolder
        name: Hello world action step
        with:
          min: ${{ secrets.MINIMUM }}
          max: ${{ secrets.MAXIMUM }}

      - name: Running index.js in MAIN
        run: node index.js
        env:
          MINIMUM: ${{ secrets.MINIMUM }}
          MAXIMUM: ${{ secrets.MAXIMUM }}
