name: Main

jobs:
  main-flow:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Running index.js
        run: node index.js
