name: Reusable workflow for submodule

on: [workflow_call]

defaults:
  run:
    working-directory: subfolder

jobs:
  main-flow:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/do_action