name: Reusable workflow for submodule

on:
  workflow_call:

defaults:
  run:
    working-directory: subfolder

jobs:
  main-flow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Running index.js in SUBFOLDER
        run: node index.js
        env:
          MAXIMUM_SUBFOLDER: ${{ secrets.MINIMUM }}
          MINIMUM_SUBFOLDER: ${{ secrets.MAXIMUM }}