name: Reusable workflow for submodule

on: [workflow_dispatch, workflow_call]

defaults:
  run:
    working-directory: subfolder

jobs:
  sub-flow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Running index.js in SUBFOLDER
        run: node ./sub/index.js
        env:
          MAXIMUM_SUBFOLDER: ${{ secrets.MINIMUM }}
          MINIMUM_SUBFOLDER: ${{ secrets.MAXIMUM }}