name: Telegram Notify
on: [push]
jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          debug: true
          format: markdown
          message: |
            ## New Commit
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            ## Repo
            Repository: ${{ github.repository }}

            ### Commit Info
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
