name: Telegram Notify

on:
  pull_request:
    types: [opened]
    branches: [staging]

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          debug: true
          format: html
          message: |
            <h3>New Commit</h3>
            ${{ github.actor }} created a new PR in ${{ github.repository }}:
            PR title: ${{ github.event.pull_request.title }}

            <h4>Commit Info</h4>
            See changes: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
