name: Telegram Notify

on:
  pull_request:
    types: [opened]
    branches: [staging]

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          debug: true
          format: html
          message: |
            ********************

            <b>New Pull Request into ${{ github.event.pull_request.head.ref }}</b>

            <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a> has received a new pull request from <a href="https://github.com/${{ github.actor }}">${{ github.actor }}</a>

            <u>Title</u>: ${{ github.event.pull_request.title }} 👀
            <u>Link</u>: https://github.com/${{ github.repository }}/pull/${{ github.event.number }} 👀

            ********************
