name: Telegram Notify

on:
  pull_request:
    types: [opened]
    branches: [staging]

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          debug: true
          format: html
          message: |
            ********************

            <b>New Pull Request into ${{ github.event.pull_request.head.ref }}</b>

            <i>${{ github.repository }}</i> has received a new pull request from ${{ github.actor }}

            <b>Title</b>: ${{ github.event.pull_request.title }} 👀
            <b>Link</b>: https://github.com/${{ github.repository }}/pull/${{ github.event.number }} 👀

            ********************
